version: '3.8'
services:
  db:
    container_name: simple-projects-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  cache:
    container_name: simple-projects-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local