// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: posts.sql

package repository

import (
	"context"
)

const createPosts = `-- name: CreatePosts :exec
INSERT INTO posts (content) VALUES ($1)
`

func (q *Queries) CreatePosts(ctx context.Context, content string) error {
	_, err := q.db.ExecContext(ctx, createPosts, content)
	return err
}
