// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"context"
)

type Querier interface {
	CreatePosts(ctx context.Context, content string) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	GetUser(ctx context.Context, email string) (User, error)
	Registration(ctx context.Context, arg RegistrationParams) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
}

var _ Querier = (*Queries)(nil)
