// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: transactions.sql

package repository

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (user_id, amount, currency, status) VALUES ($1, $2, $3, $4)
`

type CreateTransactionParams struct {
	UserID   string `json:"user_id"`
	Amount   string `json:"amount"`
	Currency string `json:"currency"`
	Status   string `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	return err
}
